#!/usr/bin/env bash

project_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" > /dev/null && pwd )"
image_name="auto_bartender"
tag="0.1"

(cd "$project_dir" && docker build -t $image_name:$tag -f docker/Dockerfile .)

