#!/usr/bin/env bash
set -e

project_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" > /dev/null && pwd )"
current_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null && pwd )"
source $current_dir/.tag

docker run -p 3001:3001 -it $image_name:$image_tag