#!/usr/bin/env bash

PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}"/../../ )" > /dev/null && pwd )"

sudo apt-get update

sudo apt-get install -y --no-install-recommends \
  apt-transport-https lsb-release \
  ca-certificates gcc g++ make

echo "Installing NodeJS..."
wget -qO- https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs

echo "Installing UI dependencies..."
(cd $SCRIPT_DIR/ui && npm install)